language: node_js
node_js:
  - "lts/*"
cache:
  directories:
  - node_modules
script:
  - npm run build
deploy:
  provider: firebase
  token:
    secure: "1/vr8HV5QoNRAVejOchCuje4-VbBd4GnOVru205mLQEkNXMMzjVdO5NU3aYxuKZFlN"
  message: "deploy via Travis CI"
  skip_cleanup: true
  local_dir: build
  on:
    branch: nossas-rotas-map
